### ISSUE TITLE
How to Install the code for using it ?

### ISSUE THREAD

**Issue by shiroze** [Egregius/PHP-Custom-Floorplan-for-Domoticz#2]
I always get error and don't know how to install the code ? it always redirect to my localhost/dashboard

**Comment by Egregius** [comment]
A lot of information is available at https://www.domoticz.com/forum/viewtopic.php?f=8&t=7551
What error are you getting? 
Should be not much more the copying the files into your webservers folder and make some adjustments for ip addresses etc.

**Comment by shiroze** [comment]
well I try testing it on localhost to see how it works, but when I copy paste the file and try open it, it say error on secure/settings.php (maybe the path that is wrong). after changing the path my browser automatically redirect to localhost/dashboard

**Comment by Egregius** [comment]
What is the exact error? 
And what do you mean by the redirect? There's no redirect in the code.
Please be more specific.

**Comment by shiroze** [comment]
Never mind, I just want to test implement the FloorPlan in my own website php. But Looks like im in wrong section thanks for the Time Owner.
